### ISSUE TITLE
Installation instructions page does not show tab contents

### ISSUE THREAD

**Issue by filips123** [filips123/PWAsForFirefox#368]
### Description

The extension does not display the contents of the installation instructions tabs. This makes it impossible for users to see the installation instructions and download the native connector.

### Steps to Reproduce

1. Install extension version 2.7.0 or 2.7.1.
2. Click on the outdated version notification.
3. See that installation instructions are not displayed.

### Additional Information

Seems to be a problem with the build tool, as it only occurs in production builds, and maybe also affects other parts of the extension. Initially reported [here](https://github.com/filips123/PWAsForFirefox/discussions/367#discussioncomment-6480211) and via email.

Affected versions (2.7.0 and 2.7.1) have been disabled on AMO. If you have this problem, downgrade the extension to 2.6.1 until a proper fix is released.

### Environment

* PWAsForFirefox extension version: 2.7.0, 2.7.1
* PWAsForFirefox native version: different than the extension version
* Firefox version: 115.0.2, 117.0a1

**Comment by filips123** [comment]
Now I released [2.7.2](https://github.com/filips123/PWAsForFirefox/releases/tag/v2.7.2) that hopefully fixed this issue.

**Comment by Inrumpo** [comment]
This seems to work on my end. Thank you.

**Comment by eturker** [comment]
Issue still present.

EndeavourOS 
Firefox 116.0
firefox-pwa 2.7.2

**Comment by filips123** [comment]
Please open developer tools (F12 and console) and check if there are any errors.

**Comment by filips123** [comment]
This is #378. I will release the fix soon.
